# Generated by Django 4.2.1 on 2023-05-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('img', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField(max_length=5)),
                ('price', models.IntegerField(max_length=5)),
                ('Desc', models.TextField(max_length=500)),
                ('T_price', models.IntegerField(max_length=10)),
            ],
        ),
    ]
