# Generated by Django 4.2.1 on 2023-05-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_icdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icdetails',
            name='T_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='icdetails',
            name='img',
            field=models.ImageField(upload_to='home_imgs'),
        ),
        migrations.AlterField(
            model_name='icdetails',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='icdetails',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
