# Generated by Django 4.2.1 on 2023-05-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_icdetails_t_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ICDetails',
            new_name='ICDetail',
        ),
    ]
