# Generated by Django 4.2.1 on 2023-06-08 11:39

import autoslug.fields
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_icdetails_icdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='icdetail',
            name='icecream_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='icdetail',
            name='Desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
